### PR TITLE
Revert "Build: Make dex2oat boot image error abort explicit"

### PR DESCRIPTION
**Pull request by Verevka**
This reverts commit 5ccf0900d0d0c568a5c58ab9ffd9e6349e845c52.

### CODE REVIEW

**Comment by Chityanj** [comment]
Can I know the error?

**Comment by Verevka** [comment]
-
oj.jar          --abort-on-hard-verifier-error          --ab
ort-on-soft-verifier-error               --generate-mini-deb
ug-info                 || ( echo \"ERROR: Dex2oat failed to
 compile a boot image. It is likely that the boot classpath
is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=\"--
runtime-arg -verbose:verifier\" to see verification errors.\
" ; false ) &&  ANDROID_LOG_TAGS=\"*:e\" ANDROID_ROOT=/home/
vetochkinvalera2/revenge/out/target/product/sagit/system AND
ROID_DATA=/home/vetochkinvalera2/revenge/out/target/product/
sagit/dex_bootjars/system/framework/arm64/ /home/vetochkinva
lera2/revenge/out/host/linux-x86/bin/patchoatd          --in
put-image-location=/home/vetochkinvalera2/revenge/out/target
/product/sagit/dex_bootjars/system/framework/boot.art      -
-output-image-relocation-directory=/home/vetochkinvalera2/re
venge/out/target/product/sagit/dex_bootjars/system/framework
/arm64/                 --instruction-set=arm64            -
-base-offset-delta=0x10000000 )"
dex2oatd F 02-19 11:48:45  7732  7732 compiler_driver.cc:942
] Had 2 soft failure(s) verifying all classes, and was asked
 to abort in such situations. Please check the log.
ERROR: Dex2oat failed to compile a boot image. It is likely
that the boot classpath is inconsistent. Rebuild with ART_BO
OT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier to see v
erification errors.

**Comment by Verevka** [comment]
] Had 2 soft failure(s) verifying all classes, and was asked
 to abort in such situations. Please check the log.
ERROR: Dex2oat failed to compile a boot image. It is likely
that the boot classpath is inconsistent. Rebuild with ART_BO
OT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier to see v
erification errors.

**Comment by Lucchetto** [comment]
Bro PM me

**Comment by ghost** [comment]
I am having the same issue , anyone getting it working

**Pull request closed without merging**
